FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Installa pacchetti di base e strumenti di sviluppo
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    gdb \
    make \
    vim \
    git \
    cmake \
    wget \
    unzip \
    libpthread-stubs0-dev


# Alias
RUN echo "alias build='rm -rf build && mkdir build && cd ./build && cmake .. && time make -j$(nproc) && cd ..'" >> ~/.bashrc


WORKDIR /workspace
CMD ["/bin/bash"]
